---
language: ruby
cache: bundler
script: script/test
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.1
before_install: gem install bundler
addons:
 apt:
   packages:
     - libgmp-dev
